### ISSUE TITLE
Node 6.0+ support is broken

### ISSUE THREAD

**Issue by nullptr128** [gordonmleigh/promised-mongo#51]
Hello!

Promised-Mongo unfortunately does not work on Node 6.0 at all, while it works correctly in Node 4.X.

It keeps crashing on /promised-mongo/dist/Cursor.js:65

```
case 3:
            this._cursor = context$2$0.sent.cursor(this.namespace, this.command, this.options);
```

Saying that send.cursor is not a function. I am not sure if it is only your file or whole regenerator runtime is broken on 6.0 but as far as I know, you can use babel-plugin-transform-async-to-generator instead as generator methods are supported on 6.0.

**Comment by Ice32** [comment]
Having the same issue here, **it works on Node 5.0.0**, but I'm getting "context$2$0.sent.cursor is not a function" on 6.0.0

**Comment by Wolke** [comment]
same issue

**Comment by kpdecker** [comment]
Root issue here is that _serverPromise is not set, which breaks the proxy generator here:
https://github.com/gordonmleigh/promised-mongo/blob/master/index.js#L28

Confirmed that the cursor issue above is fixed when changing that to remove `_serverPromise` from the collection generation logic, but this feels like whackamole, so I'm not sure what the ideal fix would be here.

**Comment by Darkhogg** [comment]
That is not the only issue, however. As soon as I try to connect I get various errors about not being able to add `_id` to a string, or about Symbols not being strings, etc.

This is a serious issue!

**Comment by ivan133** [comment]
So, it shouldn't work with nove 6+, right?

**Comment by Dussed** [comment]
Had a similar issue using Node 6.11.0 - I've found dropping [then-mongo](https://github.com/then/then-mongo) in place works for me, with a few minor changes (pretty much just imports) - it's also based off of mongojs
